import { TrainingModality } from '../../domain/models.js';

export const conditioningCatalog = [
  // Running / cycling conditioning
  {
    id: 'run-zone2',
    name: 'Carrera suave en Zona 2',
    modalities: [TrainingModality.RUNNING, TrainingModality.MIXED],
    sessionTypes: ['aerobic'],
    category: 'cardio_base',
    equipment: 'Zapatillas',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Ritmo conversacional', 'Cadencia estable', 'Respiración controlada'],
  },
  {
    id: 'run-tempo',
    name: 'Carrera a ritmo (Tempo Run)',
    modalities: [TrainingModality.RUNNING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_threshold',
    equipment: 'Zapatillas',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Ritmo sostenido subumbral', 'Técnica eficiente', 'No salir demasiado rápido'],
  },
  {
    id: 'run-intervals',
    name: 'Intervalos de carrera',
    modalities: [TrainingModality.RUNNING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_interval',
    equipment: 'Zapatillas',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Recuperaciones completas', 'Calidad sobre cantidad', 'Mecánica consistente'],
  },
  {
    id: 'run-strides',
    name: 'Aceleraciones progresivas (Strides)',
    modalities: [TrainingModality.RUNNING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_skill',
    equipment: 'Zapatillas',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Aceleración progresiva', 'Pisada reactiva', 'Recuperación completa entre repeticiones'],
  },
  {
    id: 'run-hill-repeats',
    name: 'Cuestas (Hill Repeats)',
    modalities: [TrainingModality.RUNNING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_interval',
    equipment: 'Zapatillas + cuesta',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Leve inclinación del tronco', 'Impulso potente', 'Baja caminando para recuperar'],
  },
  {
    id: 'run-a-skip-drill',
    name: 'Técnica de carrera (A-Skip)',
    modalities: [TrainingModality.RUNNING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_skill',
    equipment: 'Zapatillas',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Rodilla arriba con ritmo', 'Pisa debajo del centro de masa', 'Brazos coordinados'],
  },
  {
    id: 'run-fartlek',
    name: 'Fartlek',
    modalities: [TrainingModality.RUNNING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_threshold',
    equipment: 'Zapatillas',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Alterna ritmos con control', 'Mantén técnica estable', 'No conviertas todo en sprint'],
  },
  {
    id: 'cycle-zone2',
    name: 'Ciclismo en Zona 2',
    modalities: [TrainingModality.CYCLING, TrainingModality.MIXED],
    sessionTypes: ['aerobic'],
    category: 'cardio_base',
    equipment: 'Bicicleta',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Cadencia cómoda', 'Pulso estable', 'Hidratación durante sesión'],
  },
  {
    id: 'cycle-cadence-drill',
    name: 'Técnica de cadencia (Ciclismo)',
    modalities: [TrainingModality.CYCLING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_skill',
    equipment: 'Bicicleta',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Sube rpm progresivo', 'Evita rebote de cadera', 'Mantén control respiratorio'],
  },
  {
    id: 'cycle-intervals',
    name: 'Intervalos de ciclismo',
    modalities: [TrainingModality.CYCLING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_interval',
    equipment: 'Bicicleta',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Bloques intensos definidos', 'Recuperación activa', 'Técnica estable'],
  },
  {
    id: 'cycle-low-cadence-climb',
    name: 'Subida a baja cadencia',
    modalities: [TrainingModality.CYCLING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_threshold',
    equipment: 'Bicicleta',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Cadencia baja controlada', 'Tronco estable', 'Empuja y tira redondo'],
  },
  {
    id: 'cycle-spin-ups',
    name: 'Aceleraciones de cadencia (Spin-ups)',
    modalities: [TrainingModality.CYCLING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_skill',
    equipment: 'Bicicleta',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Sube rpm sin rebotar', 'Hombros relajados', 'Mantén línea de rodilla'],
  },
  {
    id: 'cycle-standing-climb',
    name: 'Subida de pie (Ciclismo)',
    modalities: [TrainingModality.CYCLING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_interval',
    equipment: 'Bicicleta',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Balance controlado', 'Cadencia suficiente', 'No bloquees brazos'],
  },
  {
    id: 'cycle-sweet-spot',
    name: 'Intervalos sweet spot',
    modalities: [TrainingModality.CYCLING],
    sessionTypes: ['aerobic', 'mixed'],
    category: 'cardio_threshold',
    equipment: 'Bicicleta',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Esfuerzo sostenido controlado', 'Respiración potente pero estable', 'Mantén cadencia eficiente'],
  },
];
