import { TrainingModality } from '../../domain/models.js';

export const pilatesRecoveryCatalog = [
  // Pilates & recovery
  {
    id: 'pilates-hundred',
    name: 'Pilates Hundred',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Costillas abajo', 'Respiración segmentada', 'Piernas al nivel tolerable'],
  },
  {
    id: 'pilates-roll-up',
    name: 'Pilates Roll-up',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core_mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Articula columna', 'Control excéntrico', 'No tirar del cuello'],
  },
  {
    id: 'pilates-single-leg-stretch',
    name: 'Single Leg Stretch',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Lumbar neutra', 'Movimiento fluido', 'Core activo todo el tiempo'],
  },
  {
    id: 'pilates-swimming',
    name: 'Pilates Swimming',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Extensión suave', 'Activación dorsal y glútea', 'Respiración controlada'],
  },
  {
    id: 'pilates-double-leg-stretch',
    name: 'Double Leg Stretch',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Controla costillas', 'Extiende y recoge con ritmo', 'Lumbar estable'],
  },
  {
    id: 'pilates-teaser',
    name: 'Pilates Teaser',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Sube vértebra a vértebra', 'Equilibra sobre isquiones', 'Controla la bajada'],
  },
  {
    id: 'pilates-leg-circles',
    name: 'Leg Circles',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'core_mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Pelvis quieta', 'Círculos limpios', 'Respira continuo'],
  },
  {
    id: 'pilates-side-kick-series',
    name: 'Side Kick Series',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'lower_body_unilateral',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Tronco largo', 'Pierna activa desde glúteo', 'Evita balanceo lumbar'],
  },
  {
    id: 'pilates-spine-stretch',
    name: 'Spine Stretch Forward',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Articula columna', 'Hombros relajados', 'Alarga al volver'],
  },
  {
    id: 'pilates-shoulder-bridge',
    name: 'Shoulder Bridge',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Empuja desde pie de apoyo', 'Pelvis alineada', 'Controla cada transición'],
  },
  {
    id: 'pilates-criss-cross',
    name: 'Criss-Cross',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Rota costillas, no solo codos', 'Pierna larga activa', 'Lumbar controlada'],
    progressions: ['Más tiempo', 'Pausa en cada rotación', 'Pierna más baja'],
    regressions: ['Cabeza apoyada', 'Rango corto', 'Single-leg stretch con rotación mínima'],
    contraindications: ['Dolor cervical al flexionar', 'Dolor lumbar con rotación'],
  },
  {
    id: 'pilates-open-leg-rocker',
    name: 'Open Leg Rocker',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core_mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Equilibra sobre isquiones', 'Mantén pecho alto', 'Rueda sin colapsar cuello'],
    progressions: ['Piernas más extendidas', 'Más repeticiones continuas', 'Entrada desde teaser'],
    regressions: ['Rodillas más flexionadas', 'Rolling like a ball', 'Balance estático'],
    contraindications: ['Dolor cervical', 'Lumbalgia en flexión repetida'],
  },
  {
    id: 'pilates-rolling-like-a-ball',
    name: 'Rolling Like a Ball',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core_mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Redondea uniforme', 'No apoyes cuello', 'Regresa al equilibrio con control'],
    progressions: ['Más repeticiones', 'Pausa en balance', 'Transición a open leg rocker'],
    regressions: ['Balance sin rodar', 'Rango corto', 'Apoyo de pies'],
    contraindications: ['Dolor cervical', 'Vértigo con rodamiento'],
  },
  {
    id: 'pilates-saw',
    name: 'Pilates Saw',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Siéntate alto antes de girar', 'Rota desde dorsal', 'Alarga el retorno'],
    progressions: ['Más rango con control', 'Pausa al final', 'Piernas más abiertas'],
    regressions: ['Rodillas flexionadas', 'Rango corto', 'Spine stretch forward'],
    contraindications: ['Dolor lumbar en torsión', 'Irritación isquios intensa'],
  },
  {
    id: 'pilates-single-leg-kick',
    name: 'Single Leg Kick',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Pecho abierto', 'Patada doble controlada', 'Abdomen sostiene la pelvis'],
    progressions: ['Más tiempo', 'Mayor extensión torácica', 'Tempo sostenido'],
    regressions: ['Apoyo más bajo', 'Rango pequeño', 'Una pierna a la vez lento'],
    contraindications: ['Dolor lumbar en prono', 'Molestia anterior de hombro'],
  },
  {
    id: 'pilates-double-leg-kick',
    name: 'Double Leg Kick',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Talones hacia glúteos', 'Extiende pecho al cambiar', 'Mantén abdomen largo'],
    progressions: ['Más tiempo', 'Pausa en extensión', 'Mayor control de piernas unidas'],
    regressions: ['Single leg kick', 'Menor rango', 'Apoyo más cómodo de cabeza'],
    contraindications: ['Dolor lumbar en extensión', 'Cervicalgia en prono'],
  },
  {
    id: 'pilates-bridge-march',
    name: 'Bridge March',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Pelvis nivelada', 'Marcha lenta', 'Empuja desde el pie de apoyo'],
    progressions: ['Mayor tiempo', 'Pausa por pierna', 'Banda sobre rodillas'],
    regressions: ['Shoulder bridge simple', 'Levantamiento mínimo de pie', 'Bridge bilateral'],
    contraindications: ['Dolor sacroilíaco', 'Calambre isquiotibial recurrente'],
  },
  {
    id: 'pilates-side-bend',
    name: 'Side Bend',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Empuja fuerte el suelo', 'Cadera asciende en arco', 'Cuello largo'],
    progressions: ['Más repeticiones controladas', 'Pausa arriba', 'Piernas largas apiladas'],
    regressions: ['Side plank con rodilla apoyada', 'Apoyo elevado', 'Isométrico corto'],
    contraindications: ['Dolor de hombro en carga', 'Dolor lateral lumbar'],
  },
  {
    id: 'pilates-mermaid-stretch',
    name: 'Mermaid Stretch',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Siéntate sobre ambos isquiones', 'Crea arco lateral largo', 'Respira hacia costillas'],
    progressions: ['Más tiempo por lado', 'Mayor alcance', 'Transición fluida entre lados'],
    regressions: ['Sentarse sobre bloque', 'Apoyo de mano más cerca', 'Rango cómodo'],
    contraindications: ['Dolor lateral de rodilla por posición', 'Limitación severa de cadera'],
  },
  {
    id: 'pilates-neck-pull',
    name: 'Neck Pull',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core_mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Codos amplios', 'Sube articulando columna', 'Bisagra al frente sin colapsar'],
    progressions: ['Piernas ancladas firmes', 'Tempo lento', 'Mayor control excéntrico'],
    regressions: ['Roll-up', 'Rodillas flexionadas', 'Manos cruzadas al pecho'],
    contraindications: ['Dolor cervical', 'Lumbalgia en flexión'],
  },
  {
    id: 'pilates-shoulder-bridge-kick',
    name: 'Shoulder Bridge Kick',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'lower_body_unilateral',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Pelvis sigue alta', 'Pierna libre sube sin girar cadera', 'Respira manteniendo control'],
    progressions: ['Más tiempo por lado', 'Pausa con pierna extendida', 'Banda ligera'],
    regressions: ['Bridge march', 'Shoulder bridge simple', 'Extensión parcial de rodilla'],
    contraindications: ['Dolor lumbar al elevar pierna', 'Pérdida de estabilidad pélvica marcada'],
  },
  {
    id: 'pilates-scissors',
    name: 'Scissors',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'pilates scissors proper form tutorial',
    cues: ['Pelvis estable', 'Pierna superior se alarga', 'Evita tirar del cuello'],
    progressions: ['Piernas más extendidas', 'Más tiempo', 'Pausa breve en cada cambio'],
    regressions: ['Rodillas flexionadas', 'Cabeza apoyada', 'Single leg stretch'],
    contraindications: ['Tensión cervical alta', 'Dolor lumbar en flexión'],
  },
  {
    id: 'pilates-double-leg-lower-lift',
    name: 'Double Leg Lower Lift',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'pilates double leg lower lift proper form',
    cues: ['Costillas contenidas', 'Piernas descienden solo hasta sostener lumbar', 'Sube sin impulso'],
    progressions: ['Piernas más bajas', 'Más tiempo', 'Pausa cerca del suelo'],
    regressions: ['Rodillas semiflexionadas', 'Rango corto', 'Dead bug'],
    contraindications: ['Diástasis no controlada', 'Dolor lumbar al bajar piernas'],
  },
  {
    id: 'pilates-front-support',
    name: 'Front Support',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'pilates front support proper form',
    cues: ['Empuja el suelo', 'Escápulas estables', 'Línea larga de cabeza a talones'],
    progressions: ['Más tiempo', 'Shoulder tap lento', 'Leg pull front'],
    regressions: ['Rodillas apoyadas', 'Apoyo elevado', 'Bloques cortos'],
    contraindications: ['Dolor de muñeca', 'Dolor lumbar al perder control'],
  },
  {
    id: 'pilates-leg-pull-front',
    name: 'Leg Pull Front',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'pilates leg pull front proper form',
    cues: ['Cuerpo en bloque', 'Pierna sube sin girar pelvis', 'Hombros se mantienen lejos de orejas'],
    progressions: ['Más tiempo', 'Pausa con pierna arriba', 'Alternancia continua'],
    regressions: ['Front support', 'Pierna más baja', 'Rodillas apoyadas'],
    contraindications: ['Dolor de hombro en carga', 'Dolor lumbar al levantar pierna'],
  },
  {
    id: 'pilates-leg-pull-back',
    name: 'Leg Pull Back',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'pilates leg pull back proper form',
    cues: ['Pecho abierto', 'Cadera alta', 'Pierna se eleva sin colapsar hombros'],
    progressions: ['Más tiempo', 'Pausa por repetición', 'Entrada desde reverse plank'],
    regressions: ['Reverse plank estático', 'Pierna más baja', 'Manos elevadas'],
    contraindications: ['Dolor anterior de hombro', 'Molestia lumbar en extensión'],
  },
  {
    id: 'pilates-seal',
    name: 'Seal',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core_mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'pilates seal proper form',
    cues: ['Equilibra sobre isquiones', 'Aplausos pequeños con piernas', 'Rueda sin caer sobre cuello'],
    progressions: ['Más repeticiones', 'Mayor control al volver', 'Salida a standing'],
    regressions: ['Rolling like a ball', 'Balance estático', 'Rango corto'],
    contraindications: ['Vértigo con rodamiento', 'Dolor cervical'],
  },
  {
    id: 'pilates-twist',
    name: 'Pilates Twist',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core_mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'pilates twist proper form seated',
    cues: ['Siéntate alto', 'Rota desde dorsal', 'Piernas activas y quietas'],
    progressions: ['Más tiempo por lado', 'Pulsos pequeños al final', 'Entrada desde saw'],
    regressions: ['Rodillas flexionadas', 'Rango corto', 'Hands behind hips'],
    contraindications: ['Dolor lumbar con torsión', 'Irritación isquiotibial al sentarse recto'],
  },
  {
    id: 'pilates-jackknife',
    name: 'Jackknife',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'pilates jackknife proper form',
    cues: ['Sube pelvis en línea', 'Piernas largas hacia techo', 'Baja articulando sin golpe'],
    progressions: ['Más control excéntrico', 'Pausa vertical', 'Transición desde rollover'],
    regressions: ['Hip lift corto', 'Open leg rocker', 'Support under pelvis'],
    contraindications: ['Dolor cervical', 'Hipertensión no controlada', 'Lumbalgia en flexión'],
  },
  {
    id: 'pilates-wall-roll-down',
    name: 'Wall Roll Down',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Pared',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'pilates wall roll down proper form',
    cues: ['Espalda inicia pegada a pared', 'Despega vértebra a vértebra', 'Regresa con control'],
    progressions: ['Más recorrido', 'Brazos al frente', 'Mayor tiempo en flexión'],
    regressions: ['Rango corto', 'Rodillas suaves', 'Apoyo de manos en muslos'],
    contraindications: ['Mareo ortostático', 'Dolor lumbar al flexionar'],
  },
  {
    id: 'pilates-side-lying-clam',
    name: 'Side-Lying Clam',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'lower_body_unilateral',
    equipment: 'Mat o miniband',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'pilates side lying clam proper form',
    cues: ['Talones juntos', 'Pelvis quieta', 'Abre desde cadera y no desde espalda'],
    progressions: ['Miniband', 'Pausa arriba', 'Más tiempo por lado'],
    regressions: ['Rango corto', 'Sin banda', 'Soporte bajo cabeza'],
    contraindications: ['Dolor lateral de cadera al comprimir', 'Irritación lumbar si rota pelvis'],
  },
  {
    id: 'pilates-swan-prep',
    name: 'Swan Prep',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'pilates swan prep proper form',
    cues: ['Esternón se desliza adelante', 'Glúteos suaves activos', 'Extiende sin comprimir lumbar'],
    progressions: ['Más altura', 'Pausa arriba', 'Transición a swan completo'],
    regressions: ['Cobra baja', 'Rango corto', 'Toalla bajo esternón'],
    contraindications: ['Dolor lumbar en extensión', 'Cervicalgia en prono'],
  },
  {
    id: 'pilates-standing-roll-down',
    name: 'Standing Roll Down',
    modalities: [TrainingModality.PILATES],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Sin equipo',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'pilates standing roll down proper form',
    cues: ['Mentón suave al pecho', 'Articula columna en secuencia', 'Sube apilando vértebras'],
    progressions: ['Más recorrido', 'Pausa abajo', 'Entrada con brazos overhead'],
    regressions: ['Manos en muslos', 'Rodillas suaves', 'Wall roll down'],
    contraindications: ['Mareo al descender', 'Dolor neural posterior al inclinarse'],
  },
  {
    id: 'gym-hack-squat',
    name: 'Hack Squat',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'lower_body_strength',
    equipment: 'Máquina hack squat',
    loadType: 'external',
    loadRatio: 0.62,
    cues: ['Espalda apoyada', 'Rodillas viajan con control', 'Profundidad sin despegar cadera'],
  },
  {
    id: 'gym-chest-supported-row',
    name: 'Chest-Supported Row',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Banco inclinado + mancuernas',
    loadType: 'external',
    loadRatio: 0.18,
    cues: ['Pecho fijo en banco', 'Tira con codos', 'Sin impulso lumbar'],
  },
  {
    id: 'gym-leg-curl',
    name: 'Leg Curl',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'Máquina curl femoral',
    loadType: 'external',
    loadRatio: 0.18,
    cues: ['Cadera estable', 'Curl completo sin rebote', 'Excéntrica lenta'],
  },
  {
    id: 'gym-cable-fly',
    name: 'Cable Fly',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Poleas',
    loadType: 'external',
    loadRatio: 0.1,
    cues: ['Abrazo amplio', 'Pecho arriba', 'Tensión continua'],
  },
  {
    id: 'gym-lateral-raise',
    name: 'Lateral Raise',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Mancuernas o polea',
    loadType: 'external',
    loadRatio: 0.06,
    cues: ['Codo suave', 'Sube hasta línea del hombro', 'Evita balanceo'],
  },
  {
    id: 'gym-triceps-pushdown',
    name: 'Triceps Pushdown',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Polea',
    loadType: 'external',
    loadRatio: 0.1,
    cues: ['Codos pegados', 'Extiende sin inclinar tronco', 'Controla la subida'],
  },
  {
    id: 'gym-db-curl',
    name: 'Dumbbell Curl',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Mancuernas',
    loadType: 'external',
    loadRatio: 0.08,
    cues: ['Codos quietos', 'Supina completo', 'No uses impulso'],
  },
  {
    id: 'mobility-ankle',
    name: 'Ankle Mobility Drill',
    modalities: [
      TrainingModality.FULL_GYM,
      TrainingModality.HOME,
      TrainingModality.TRX,
      TrainingModality.RUNNING,
      TrainingModality.CYCLING,
      TrainingModality.MIXED,
    ],
    sessionTypes: ['recovery', 'mindbody'],
    category: 'mobility',
    equipment: 'Sin equipo',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Recorrido sin dolor', 'Control articular', 'Ritmo lento'],
  },
  {
    id: 'mobility-thoracic',
    name: 'Thoracic Rotation Drill',
    modalities: [
      TrainingModality.FULL_GYM,
      TrainingModality.HOME,
      TrainingModality.TRX,
      TrainingModality.RUNNING,
      TrainingModality.CYCLING,
      TrainingModality.YOGA,
      TrainingModality.PILATES,
      TrainingModality.MIXED,
    ],
    sessionTypes: ['recovery', 'mindbody'],
    category: 'mobility',
    equipment: 'Sin equipo',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Evita compensar lumbar', 'Respiración profunda', 'Rango progresivo'],
  },
  {
    id: 'recovery-walk',
    name: 'Recovery Walk',
    modalities: [TrainingModality.FULL_GYM, TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['recovery'],
    category: 'recovery',
    equipment: 'Sin equipo',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Ritmo suave', 'Respiración nasal', 'Enfócate en bajar pulso'],
  },
];
