import { TrainingModality } from '../../domain/models.js';

export const strengthCatalog = [
  // Full gym strength / hypertrophy
  {
    id: 'gym-barbell-back-squat',
    name: 'Barbell Back Squat',
    modalities: [TrainingModality.FULL_GYM, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_strength',
    equipment: 'Barbell + Rack',
    loadType: 'external',
    loadRatio: 0.45,
    cues: ['Pies firmes y alineados', 'Columna neutra', 'Profundidad controlada sin perder técnica'],
  },
  {
    id: 'gym-front-squat',
    name: 'Front Squat',
    modalities: [TrainingModality.FULL_GYM, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_strength',
    equipment: 'Barbell + Rack',
    loadType: 'external',
    loadRatio: 0.38,
    cues: ['Codos altos', 'Core activo', 'Rodillas siguen línea de pies'],
  },
  {
    id: 'gym-romanian-deadlift',
    name: 'Romanian Deadlift',
    modalities: [TrainingModality.FULL_GYM, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'Barbell o dumbbells',
    loadType: 'external',
    loadRatio: 0.4,
    cues: ['Bisagra de cadera', 'Espalda neutra', 'Recorrido hasta tensión femoral'],
  },
  {
    id: 'gym-conventional-deadlift',
    name: 'Conventional Deadlift',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'Barbell',
    loadType: 'external',
    loadRatio: 0.5,
    cues: ['Barra pegada al cuerpo', 'Empuje de suelo', 'Bloqueo final sin hiperextender'],
  },
  {
    id: 'gym-bench-press',
    name: 'Barbell Bench Press',
    modalities: [TrainingModality.FULL_GYM, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Barbell + Bench',
    loadType: 'external',
    loadRatio: 0.35,
    cues: ['Escápulas retraídas', 'Apoyo completo de pies', 'Recorrido estable y controlado'],
  },
  {
    id: 'gym-incline-db-press',
    name: 'Incline Dumbbell Press',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Dumbbells + Bench',
    loadType: 'external',
    loadRatio: 0.18,
    cues: ['Control excéntrico', 'Ángulo 30-45°', 'Evita cerrar hombros'],
  },
  {
    id: 'gym-overhead-press',
    name: 'Overhead Press',
    modalities: [TrainingModality.FULL_GYM, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Barbell o dumbbells',
    loadType: 'external',
    loadRatio: 0.22,
    cues: ['Glúteos activos', 'Trayectoria vertical', 'No hiperextender lumbar'],
  },
  {
    id: 'gym-lat-pulldown',
    name: 'Lat Pulldown',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Polea',
    loadType: 'external',
    loadRatio: 0.22,
    cues: ['Depresión escapular', 'Controlar rebote', 'Llevar codos al costado'],
  },
  {
    id: 'gym-seated-row',
    name: 'Seated Cable Row',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Polea',
    loadType: 'external',
    loadRatio: 0.22,
    cues: ['Pecho abierto', 'Tira con espalda', 'Fase excéntrica lenta'],
  },
  {
    id: 'gym-barbell-row',
    name: 'Barbell Row',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Barbell',
    loadType: 'external',
    loadRatio: 0.32,
    cues: ['Bisagra estable', 'Evita impulso', 'Barra hacia abdomen bajo'],
  },
  {
    id: 'gym-leg-press',
    name: 'Leg Press',
    modalities: [TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'lower_body_strength',
    equipment: 'Máquina leg press',
    loadType: 'external',
    loadRatio: 0.7,
    cues: ['Rodillas alineadas', 'Control completo', 'No bloquear articulaciones'],
  },
  {
    id: 'gym-hip-thrust',
    name: 'Hip Thrust',
    modalities: [TrainingModality.FULL_GYM, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'posterior_chain',
    equipment: 'Barbell + Bench',
    loadType: 'external',
    loadRatio: 0.5,
    cues: ['Mentón recogido', 'Pausa en contracción', 'Evita hiperextensión lumbar'],
  },
  {
    id: 'gym-split-squat',
    name: 'Bulgarian Split Squat',
    modalities: [TrainingModality.FULL_GYM, TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_unilateral',
    equipment: 'Banco + dumbbells (opcional)',
    loadType: 'external',
    loadRatio: 0.14,
    cues: ['Descenso vertical', 'Rodilla estable', 'Empuja con pie delantero'],
  },
  {
    id: 'gym-face-pull',
    name: 'Face Pull',
    modalities: [TrainingModality.FULL_GYM, TrainingModality.HOME],
    sessionTypes: ['resistance', 'recovery'],
    category: 'upper_pull',
    equipment: 'Polea o banda',
    loadType: 'external',
    loadRatio: 0.08,
    cues: ['Codos altos', 'Escápulas activas', 'Control sin balanceo'],
  },
  {
    id: 'gym-calf-raise',
    name: 'Standing Calf Raise',
    modalities: [TrainingModality.FULL_GYM, TrainingModality.HOME],
    sessionTypes: ['resistance'],
    category: 'lower_body_accessory',
    equipment: 'Máquina o peso corporal',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Recorrido completo', 'Pausa arriba', 'Control de tobillo'],
  },

  // Home / bodyweight / calisthenics
  {
    id: 'home-push-up',
    name: 'Push-up',
    modalities: [TrainingModality.HOME, TrainingModality.CALISTHENICS, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_push',
    equipment: 'Peso corporal',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Cuerpo en línea', 'Codos ~45°', 'Controla el core'],
  },
  {
    id: 'home-incline-push-up',
    name: 'Incline Push-up',
    modalities: [TrainingModality.HOME, TrainingModality.CALISTHENICS],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Banco/silla',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Línea corporal neutra', 'Baja pecho a apoyo', 'Empuje completo'],
  },
  {
    id: 'home-pike-push-up',
    name: 'Pike Push-up',
    modalities: [TrainingModality.HOME, TrainingModality.CALISTHENICS],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Peso corporal',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Caderas elevadas', 'Codo hacia atrás', 'Control cervical'],
  },
  {
    id: 'home-band-row',
    name: 'Band Row',
    modalities: [TrainingModality.HOME, TrainingModality.CALISTHENICS, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Banda elástica',
    loadType: 'external',
    loadRatio: 0.1,
    cues: ['Escápulas atrás', 'No elevar hombros', 'Recorrido completo'],
  },
  {
    id: 'home-band-chest-press',
    name: 'Band Chest Press',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Banda elástica',
    loadType: 'external',
    loadRatio: 0.1,
    cues: ['Ancla estable', 'Empuje horizontal limpio', 'No perder control escapular'],
  },
  {
    id: 'home-bodyweight-squat',
    name: 'Bodyweight Squat',
    modalities: [TrainingModality.HOME, TrainingModality.CALISTHENICS, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_strength',
    equipment: 'Peso corporal',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Rodillas estables', 'Pecho alto', 'Profundidad con control'],
  },
  {
    id: 'home-reverse-lunge',
    name: 'Reverse Lunge',
    modalities: [TrainingModality.HOME, TrainingModality.CALISTHENICS],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_unilateral',
    equipment: 'Peso corporal o mancuernas',
    loadType: 'external',
    loadRatio: 0.12,
    cues: ['Paso largo', 'Torso erguido', 'Empuje con pierna delantera'],
  },
  {
    id: 'home-step-up',
    name: 'Step-up',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_unilateral',
    equipment: 'Banco o escalon',
    loadType: 'external',
    loadRatio: 0.12,
    cues: ['Controla la bajada', 'Impulsa con la pierna de apoyo', 'Evita impulso excesivo'],
  },
  {
    id: 'home-single-leg-rdl',
    name: 'Single-Leg Romanian Deadlift',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'Mancuerna o mochila',
    loadType: 'external',
    loadRatio: 0.1,
    cues: ['Bisagra limpia', 'Cadera cuadrada', 'Alcanza equilibrio antes de cargar'],
  },
  {
    id: 'home-hip-bridge',
    name: 'Hip Bridge',
    modalities: [TrainingModality.HOME, TrainingModality.CALISTHENICS, TrainingModality.PILATES],
    sessionTypes: ['resistance', 'recovery'],
    category: 'posterior_chain',
    equipment: 'Peso corporal',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Activar glúteos', 'Pausa arriba', 'No hiperextender lumbar'],
  },
  {
    id: 'home-plank',
    name: 'Front Plank',
    modalities: [TrainingModality.HOME, TrainingModality.CALISTHENICS, TrainingModality.YOGA, TrainingModality.PILATES],
    sessionTypes: ['resistance', 'mixed', 'mindbody', 'recovery'],
    category: 'core',
    equipment: 'Peso corporal',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Columna neutra', 'Glúteos activos', 'Respiración nasal controlada'],
  },
  {
    id: 'home-dead-bug',
    name: 'Dead Bug',
    modalities: [TrainingModality.HOME, TrainingModality.PILATES, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mindbody', 'recovery'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Lumbar estable', 'Exhala al extender', 'Movimiento lento y simétrico'],
  },
  {
    id: 'home-side-plank',
    name: 'Side Plank',
    modalities: [TrainingModality.HOME, TrainingModality.CALISTHENICS, TrainingModality.YOGA, TrainingModality.PILATES],
    sessionTypes: ['resistance', 'mindbody', 'recovery'],
    category: 'core',
    equipment: 'Peso corporal',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Cadera alineada', 'Hombro estable', 'Respira sin colapsar tronco'],
  },
  {
    id: 'home-bird-dog',
    name: 'Bird Dog',
    modalities: [TrainingModality.HOME, TrainingModality.PILATES, TrainingModality.MIXED],
    sessionTypes: ['recovery', 'mindbody', 'resistance'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Pelvis estable', 'Alarga brazo y pierna', 'Evita rotar el tronco'],
  },
  {
    id: 'home-band-overhead-press',
    name: 'Band Overhead Press',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Banda elástica',
    loadType: 'external',
    loadRatio: 0.08,
    difficulty: 'build',
    cues: ['Costillas abajo', 'Empuja vertical sin arquear lumbar', 'Bloquea con hombro estable'],
    progressions: ['Mayor tensión de banda', 'Split stance press', 'Tempo 3-1-1'],
    regressions: ['Press unilateral', 'Medio arrodillado', 'Rango parcial sin dolor'],
    contraindications: ['Dolor subacromial agudo', 'Inestabilidad glenohumeral no controlada'],
  },
  {
    id: 'home-band-pullover',
    name: 'Band Pullover',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Banda elástica + anclaje alto',
    loadType: 'external',
    loadRatio: 0.08,
    difficulty: 'build',
    cues: ['Brazos casi extendidos', 'Costillas controladas', 'Lleva manos hacia caderas'],
    progressions: ['Mayor tensión de banda', 'Pausa al final del recorrido', 'Pullover en medio arrodillado'],
    regressions: ['Menor tensión', 'Recorrido parcial', 'Pullover unilateral'],
    contraindications: ['Dolor anterior de hombro', 'Irritación lumbar al perder control costal'],
  },
  {
    id: 'home-band-pull-apart',
    name: 'Band Pull-Apart',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'recovery'],
    category: 'upper_pull',
    equipment: 'Miniband o banda ligera',
    loadType: 'external',
    loadRatio: 0.04,
    difficulty: 'foundation',
    cues: ['Pulgares apuntan afuera', 'Escápulas se abren y cierran con control', 'No eleves hombros'],
    progressions: ['Mayor tensión', 'Pausa isométrica 2s', 'Pull-apart en Y'],
    regressions: ['Menor tensión', 'Rango corto limpio', 'Trabajo sentado'],
    contraindications: ['Dolor agudo cervical al compensar', 'Irritación de hombro si no tolera abducción'],
  },
  {
    id: 'home-banded-good-morning',
    name: 'Banded Good Morning',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'Banda elástica',
    loadType: 'external',
    loadRatio: 0.12,
    difficulty: 'build',
    cues: ['Bisagra pura de cadera', 'Rodillas suaves', 'Mantén tensión abdominal'],
    progressions: ['Mayor tensión', 'Tempo 4s bajada', 'Versión a una pierna asistida'],
    regressions: ['Banda más ligera', 'Rango parcial', 'Bisagra con palo'],
    contraindications: ['Dolor lumbar con flexión', 'Mareo al inclinarse repetidamente'],
  },
  {
    id: 'home-single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    modalities: [TrainingModality.HOME, TrainingModality.PILATES, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mindbody'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Pelvis nivelada', 'Empuja desde talón', 'No gires la cadera'],
    progressions: ['Pausa 2s arriba', 'Pie elevado', 'Banda sobre rodillas'],
    regressions: ['Bridge bilateral', 'Recorrido parcial', 'Apoyo de manos'],
    contraindications: ['Dolor isquiotibial proximal', 'Lumbalgia si no controla pelvis'],
  },
  {
    id: 'home-wall-sit',
    name: 'Wall Sit',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_strength',
    equipment: 'Pared',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Espalda apoyada completa', 'Rodillas alineadas', 'Peso repartido en toda la planta'],
    progressions: ['Más tiempo bajo tensión', 'Carga externa liviana', 'Versión unilateral asistida'],
    regressions: ['Ángulo menos profundo', 'Bloques cortos', 'Apoyo alto en pared'],
    contraindications: ['Dolor patelofemoral no tolerado', 'Crisis hipertensiva no controlada'],
  },
  {
    id: 'home-cossack-squat',
    name: 'Cossack Squat',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mindbody'],
    category: 'lower_body_unilateral',
    equipment: 'Peso corporal',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Desplaza cadera lateral', 'Pie de pierna larga apunta arriba', 'Mantén pecho abierto'],
    progressions: ['Carga goblet ligera', 'Mayor profundidad', 'Pausa isométrica abajo'],
    regressions: ['Rango parcial', 'Apoyo con TRX o silla', 'Talón elevado'],
    contraindications: ['Limitación severa de aductores', 'Dolor de rodilla medial'],
  },
  {
    id: 'home-bear-crawl',
    name: 'Bear Crawl',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['mixed'],
    category: 'conditioning',
    equipment: 'Espacio libre',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Rodillas flotan bajo cadera', 'Paso corto y silencioso', 'Espalda neutra'],
    progressions: ['Mayor distancia', 'Bear crawl lateral', 'Arrastre con miniband'],
    regressions: ['Bear hold estático', 'Recorrido corto', 'Apoyo elevado de manos'],
    contraindications: ['Dolor de muñeca no tolerado', 'Dolor lumbar al perder control'],
  },
  {
    id: 'home-mountain-climber',
    name: 'Mountain Climber',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['mixed'],
    category: 'conditioning',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Manos firmes', 'Rodilla viaja sin saltar cadera', 'Mantén hombros sobre muñecas'],
    progressions: ['Mayor velocidad con técnica', 'Cross-body climber', 'Deslizadores'],
    regressions: ['Step climber lento', 'Apoyo elevado', 'Bloques de 10-15s'],
    contraindications: ['Dolor de muñeca', 'Taquicardia no controlada'],
  },
  {
    id: 'home-suitcase-carry',
    name: 'Suitcase Carry',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'core',
    equipment: 'Mancuerna, garrafa o mochila',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Camina erguido', 'No te inclines hacia la carga', 'Paso corto y estable'],
    progressions: ['Más distancia', 'Mayor carga', 'Marcha lenta unilateral'],
    regressions: ['Carga liviana', 'Carry estático', 'Distancias cortas'],
    contraindications: ['Dolor lumbar irradiado', 'Pérdida de equilibrio marcada'],
  },
  {
    id: 'home-floor-press',
    name: 'Floor Press',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Mancuernas, kettlebells o mochila',
    loadType: 'external',
    loadRatio: 0.14,
    difficulty: 'foundation',
    youtubeQuery: 'floor press dumbbell proper form tutorial',
    cues: ['Antebrazos verticales', 'Escápulas firmes', 'Pausa suave en el suelo'],
    progressions: ['Más carga', 'Pausa de 2s abajo', 'Versión unilateral'],
    regressions: ['Carga ligera', 'Rango parcial', 'Band chest press'],
    contraindications: ['Dolor anterior de hombro', 'Parestesias al apoyar codo'],
  },
  {
    id: 'home-towel-row',
    name: 'Towel Row',
    modalities: [TrainingModality.HOME],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Toalla + puerta segura',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'towel row door anchor proper form',
    cues: ['Anclaje realmente seguro', 'Cuerpo en bloque', 'Tira con espalda y no solo brazos'],
    progressions: ['Más inclinación', 'Pausa final', 'Versión unilateral asistida'],
    regressions: ['Menor inclinación', 'Rango corto', 'Band row'],
    contraindications: ['Puerta o soporte inestable', 'Dolor agudo de codo o hombro'],
  },
  {
    id: 'home-band-lat-pulldown',
    name: 'Band Lat Pulldown',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Banda + anclaje alto',
    loadType: 'external',
    loadRatio: 0.1,
    difficulty: 'build',
    youtubeQuery: 'band lat pulldown proper form at home',
    cues: ['Pecho arriba', 'Codos bajan al costado', 'No rebotes con la banda'],
    progressions: ['Mayor tensión', 'Pausa abajo', 'Versión unilateral'],
    regressions: ['Menor tensión', 'Recorrido parcial', 'Band pullover'],
    contraindications: ['Dolor superior de hombro', 'Anclaje inseguro'],
  },
  {
    id: 'home-band-curl',
    name: 'Band Curl',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Banda elástica',
    loadType: 'external',
    loadRatio: 0.06,
    difficulty: 'foundation',
    youtubeQuery: 'band biceps curl strict form tutorial',
    cues: ['Codos quietos', 'Supina al subir', 'Evita impulso lumbar'],
    progressions: ['Mayor tensión', 'Pausa arriba', 'Curl unilateral'],
    regressions: ['Menor tensión', 'Rango corto', 'Curl alterno sentado'],
    contraindications: ['Dolor tendinoso anterior de codo', 'Irritación de muñeca en supinación'],
  },
  {
    id: 'home-band-triceps-pressdown',
    name: 'Band Triceps Pressdown',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Banda + anclaje alto',
    loadType: 'external',
    loadRatio: 0.06,
    difficulty: 'foundation',
    youtubeQuery: 'band triceps pressdown proper form at home',
    cues: ['Codos pegados', 'Extiende completo', 'No balancees el tronco'],
    progressions: ['Mayor tensión', 'Pausa abajo', 'Versión unilateral'],
    regressions: ['Menor tensión', 'Rango parcial', 'Extensión por encima de cabeza ligera'],
    contraindications: ['Dolor de codo en extensión', 'Anclaje poco estable'],
  },
  {
    id: 'home-band-lateral-raise',
    name: 'Band Lateral Raise',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Banda elástica',
    loadType: 'external',
    loadRatio: 0.04,
    difficulty: 'build',
    youtubeQuery: 'band lateral raise proper form shoulder',
    cues: ['Brazos en plano escapular', 'Codo suave', 'Sube sin encoger cuello'],
    progressions: ['Mayor tensión', 'Pausa arriba', 'Versión unilateral limpia'],
    regressions: ['Menor tensión', 'Rango corto', 'Elevación frontal parcial'],
    contraindications: ['Dolor subacromial', 'Irritación cervical si eleva hombros'],
  },
  {
    id: 'home-chair-split-squat',
    name: 'Chair Split Squat',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'lower_body_unilateral',
    equipment: 'Silla o sofá estable',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'split squat at home proper form chair support',
    cues: ['Torso vertical', 'Descenso limpio', 'Empuja con pierna delantera'],
    progressions: ['Más profundidad', 'Carga externa', 'Pausa abajo'],
    regressions: ['Apoyo de manos', 'Rango corto', 'Reverse lunge'],
    contraindications: ['Dolor de rodilla no tolerado', 'Superficie inestable'],
  },
  {
    id: 'home-skater-squat-box',
    name: 'Skater Squat to Box',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'lower_body_unilateral',
    equipment: 'Caja o banco bajo',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'skater squat to box proper form',
    cues: ['Rodilla sigue línea de pie', 'Controla la bajada', 'Usa la caja como referencia, no rebote'],
    progressions: ['Caja más baja', 'Sin caja', 'Carga goblet ligera'],
    regressions: ['Asistencia con apoyo', 'Rango parcial', 'Chair split squat'],
    contraindications: ['Dolor patelofemoral marcado', 'Pérdida de equilibrio importante'],
  },
  {
    id: 'home-single-leg-calf-raise',
    name: 'Single-Leg Calf Raise',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance'],
    category: 'lower_body_accessory',
    equipment: 'Escalón o suelo',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'single leg calf raise proper form',
    cues: ['Recorrido completo', 'Pausa arriba', 'Baja lento sin colapsar tobillo'],
    progressions: ['Más repeticiones lentas', 'Carga unilateral', 'Escalón más profundo'],
    regressions: ['Bilateral', 'Apoyo con manos', 'Rango parcial'],
    contraindications: ['Aquilodinia reactiva', 'Dolor agudo plantar'],
  },
  {
    id: 'home-hip-airplane',
    name: 'Hip Airplane',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'neuromotor',
    equipment: 'Sin equipo',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'hip airplane exercise proper form',
    cues: ['Pierna de apoyo firme', 'Abre y cierra cadera con control', 'Torso largo todo el tiempo'],
    progressions: ['Más rango de rotación', 'Sin apoyo externo', 'Bloques más largos'],
    regressions: ['Apoyo en pared', 'Rango mínimo', 'Balance unilateral simple'],
    contraindications: ['Dolor de cadera en carga', 'Inestabilidad severa de tobillo'],
  },
  {
    id: 'home-band-woodchop',
    name: 'Band Woodchop',
    modalities: [TrainingModality.HOME, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'core',
    equipment: 'Banda + anclaje medio/alto',
    loadType: 'external',
    loadRatio: 0.06,
    difficulty: 'build',
    youtubeQuery: 'band woodchop proper form core',
    cues: ['Rota desde caja torácica', 'Caderas acompañan sin colapsar', 'Brazos siguen el tronco'],
    progressions: ['Mayor tensión', 'Half-kneeling woodchop', 'Pausa al final'],
    regressions: ['Menor tensión', 'Rango corto', 'Pallof press'],
    contraindications: ['Dolor lumbar con torsión', 'Dolor costal agudo'],
  },
  {
    id: 'home-reverse-plank',
    name: 'Reverse Plank',
    modalities: [TrainingModality.HOME, TrainingModality.PILATES, TrainingModality.MIXED],
    sessionTypes: ['mindbody', 'recovery', 'resistance'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'reverse plank proper form glutes shoulders',
    cues: ['Empuja el suelo', 'Caderas altas', 'Pecho abierto sin comprimir cuello'],
    progressions: ['Marcha alterna', 'Más tiempo', 'Pierna elevada'],
    regressions: ['Reverse table top', 'Apoyo elevado', 'Bloques cortos'],
    contraindications: ['Dolor anterior de hombro', 'Muñeca dolorosa en extensión'],
  },
  {
    id: 'calis-pull-up-assisted',
    name: 'Assisted Pull-up',
    modalities: [TrainingModality.CALISTHENICS, TrainingModality.HOME, TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Barra + banda',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Depresión escapular inicial', 'No balanceo', 'Extensión completa abajo'],
  },
  {
    id: 'calis-dip-assisted',
    name: 'Assisted Dip',
    modalities: [TrainingModality.CALISTHENICS, TrainingModality.FULL_GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Paralelas + banda',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Hombros deprimidos', 'Torso estable', 'Evitar rango doloroso'],
  },
  {
    id: 'calis-inverted-row',
    name: 'Inverted Row',
    modalities: [TrainingModality.CALISTHENICS, TrainingModality.HOME],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Barra baja o mesa estable',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Cuerpo en bloque', 'Pecho hacia apoyo', 'Control excéntrico total'],
  },
  {
    id: 'calis-bench-dip',
    name: 'Bench Dip',
    modalities: [TrainingModality.CALISTHENICS, TrainingModality.HOME],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Banco o silla estable',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Hombros bajos', 'No profundizar con dolor', 'Extensión de codo controlada'],
  },
  {
    id: 'calis-hindu-push-up',
    name: 'Hindu Push-up',
    modalities: [TrainingModality.CALISTHENICS, TrainingModality.HOME],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_push',
    equipment: 'Peso corporal',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Trayectoria fluida', 'Extiende columna al final', 'Controla el retorno'],
  },
  {
    id: 'calis-hollow-hold',
    name: 'Hollow Body Hold',
    modalities: [TrainingModality.CALISTHENICS, TrainingModality.HOME, TrainingModality.PILATES],
    sessionTypes: ['resistance', 'mixed', 'mindbody'],
    category: 'core',
    equipment: 'Peso corporal',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Lumbar pegada', 'Costillas abajo', 'Respiración corta y controlada'],
  },
  {
    id: 'calis-arch-hold',
    name: 'Arch Hold',
    modalities: [TrainingModality.CALISTHENICS, TrainingModality.HOME],
    sessionTypes: ['resistance', 'mindbody'],
    category: 'posterior_chain',
    equipment: 'Peso corporal',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Activa cadena posterior', 'No hiperextender cervical', 'Mantén respiración constante'],
  },
];
