// FASE 3 — LOTE 1 de expansión del catálogo prescribible (20-jul-2026).
//
// 30 variantes clásicas de gimnasio promovidas desde exerciseLibrary (free-exercise-db,
// dominio público: TODOS tienen fotos de técnica vía mediaMap). Curación aplicada:
// - loadRatio anclado a los básicos existentes (sentadilla 0.45, banca 0.35, militar 0.22,
//   curl mancuernas 0.08…): fracción del peso corporal como carga inicial prescribible.
// - ids con TOKENS CANÓNICOS para que los filtros de comorbilidad (regex sobre id+nombre
//   en comorbidityRestrictions.js) los cacen: 'shoulder-press'/'arnold' (hombro sensible,
//   patrón AMPLIADO en este lote), 'decline'… Peso muerto SUMO permitido con lumbar
//   sensible A PROPÓSITO (torso más vertical y menos cizalla que el convencional, que
//   sigue bloqueado) — decisión documentada y testeada.
// - equipment con tokens que clasifica equipmentPreferences (barra/mancuern/polea/máquina/
//   dominadas/banco/rack…) para el filtro por material del usuario.
// - Nada de flexión espinal cargada nueva (osteoporosis-safe por diseño: pallof es
//   anti-rotación y la rueda es anti-extensión).
import { TrainingModality } from '../../domain/models.js';

const GYM = TrainingModality.FULL_GYM;
const MIXED = TrainingModality.MIXED;
const CALIS = TrainingModality.CALISTHENICS;

export const strengthCatalogExpansion = [
  // ---- Pierna: fuerza y accesorios ----
  {
    id: 'gym-goblet-squat',
    name: 'Sentadilla goblet',
    modalities: [GYM, MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_strength',
    equipment: 'Mancuerna o kettlebell',
    loadType: 'external',
    loadRatio: 0.2,
    difficulty: 'foundation',
    cues: ['Mancuerna pegada al pecho', 'Codos por dentro de las rodillas al bajar', 'Talones firmes en el suelo'],
  },
  {
    id: 'gym-leg-extension',
    name: 'Extensión de cuádriceps en máquina',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'lower_body_accessory',
    equipment: 'Máquina',
    loadType: 'external',
    loadRatio: 0.25,
    difficulty: 'foundation',
    cues: ['Espalda apoyada en el respaldo', 'Extensión completa sin golpear el tope', 'Bajada controlada de 2-3 s'],
  },
  {
    id: 'gym-seated-calf-raise',
    name: 'Elevación de talones sentado',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'lower_body_accessory',
    equipment: 'Máquina',
    loadType: 'external',
    loadRatio: 0.3,
    difficulty: 'foundation',
    cues: ['Estiramiento completo abajo', 'Pausa de 1 s arriba', 'Sin rebotes'],
  },
  {
    id: 'gym-db-lunge',
    name: 'Zancada con mancuernas',
    modalities: [GYM, MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_unilateral',
    equipment: 'Mancuernas',
    loadType: 'external',
    loadRatio: 0.12,
    difficulty: 'build',
    cues: ['Paso amplio y estable', 'Rodilla trasera hacia el suelo', 'Torso erguido, mirada al frente'],
  },
  {
    id: 'gym-db-split-squat',
    name: 'Sentadilla split con mancuernas',
    modalities: [GYM, MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_unilateral',
    equipment: 'Mancuernas',
    loadType: 'external',
    loadRatio: 0.12,
    difficulty: 'build',
    cues: ['Postura escalonada fija', 'Baja vertical, no hacia delante', 'Empuje con el talón delantero'],
  },
  // ---- Cadena posterior ----
  {
    id: 'gym-sumo-deadlift',
    name: 'Peso muerto sumo',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'Barbell',
    loadType: 'external',
    loadRatio: 0.48,
    difficulty: 'performance',
    cues: ['Pies anchos, puntas hacia fuera', 'Torso más vertical que en convencional', 'Rodillas siguen la línea de los pies'],
  },
  {
    id: 'gym-cable-pull-through',
    name: 'Pull-through en polea',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'Polea',
    loadType: 'external',
    loadRatio: 0.2,
    difficulty: 'foundation',
    cues: ['Bisagra de cadera, no sentadilla', 'Glúteos cierran el movimiento', 'Columna neutra todo el recorrido'],
  },
  {
    id: 'gym-back-extension',
    name: 'Extensión lumbar en banco',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'Banco romano',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Sube hasta la línea del cuerpo, sin hiperextender', 'Glúteos e isquios inician el movimiento', 'Bajada controlada'],
  },
  {
    id: 'gym-cable-glute-kickback',
    name: 'Patada de glúteo en polea',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'Polea',
    loadType: 'external',
    loadRatio: 0.06,
    difficulty: 'foundation',
    cues: ['Cadera estable, sin rotar', 'Extiende con el glúteo, no con la lumbar', 'Pausa breve atrás'],
  },
  // ---- Empuje ----
  {
    id: 'gym-db-bench-press',
    name: 'Press de banca con mancuernas',
    modalities: [GYM, MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_push',
    equipment: 'Dumbbells + Bench',
    loadType: 'external',
    loadRatio: 0.28,
    difficulty: 'build',
    cues: ['Escápulas retraídas', 'Recorrido algo más profundo que con barra', 'Mancuernas estables, sin chocarlas arriba'],
  },
  {
    id: 'gym-decline-bench-press',
    name: 'Press de banca declinado con barra',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Barbell + Bench',
    loadType: 'external',
    loadRatio: 0.32,
    difficulty: 'performance',
    cues: ['Piernas bien ancladas', 'Barra a la parte baja del pecho', 'Con cargas altas, pide un spotter'],
  },
  {
    id: 'gym-db-shoulder-press',
    name: 'Press de hombros con mancuernas',
    modalities: [GYM, MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Dumbbells',
    loadType: 'external',
    loadRatio: 0.16,
    difficulty: 'build',
    cues: ['Core activo, sin arquear lumbar', 'Trayectoria vertical', 'Baja hasta la altura de las orejas'],
  },
  {
    id: 'gym-arnold-press',
    name: 'Press Arnold',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Dumbbells',
    loadType: 'external',
    loadRatio: 0.12,
    difficulty: 'build',
    cues: ['Rotación suave y continua', 'Carga moderada: es un ejercicio de control', 'No bloquees los codos arriba'],
  },
  {
    id: 'gym-db-fly',
    name: 'Aperturas con mancuernas',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Dumbbells + Bench',
    loadType: 'external',
    loadRatio: 0.1,
    difficulty: 'foundation',
    cues: ['Codos con ligera flexión fija', 'Abre hasta sentir estiramiento en el pecho', 'Cierra como abrazando un tronco'],
  },
  {
    id: 'gym-machine-chest-press',
    name: 'Press de pecho en máquina',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Máquina',
    loadType: 'external',
    loadRatio: 0.35,
    difficulty: 'foundation',
    cues: ['Ajusta el asiento: agarres a la altura del pecho', 'Empuje completo sin bloquear codos', 'Vuelta controlada'],
  },
  {
    id: 'gym-pec-deck',
    name: 'Aperturas en máquina (pec deck)',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Máquina',
    loadType: 'external',
    loadRatio: 0.15,
    difficulty: 'foundation',
    cues: ['Espalda pegada al respaldo', 'Junta con el pecho, no con los brazos', 'Pausa de 1 s en el cierre'],
  },
  {
    id: 'gym-ez-skullcrusher',
    name: 'Press francés con barra EZ',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Barra EZ + Banco',
    loadType: 'external',
    loadRatio: 0.1,
    difficulty: 'build',
    cues: ['Codos fijos apuntando al techo', 'Baja a la frente con control', 'Extiende sin abrir los codos'],
  },
  {
    id: 'gym-db-triceps-kickback',
    name: 'Patada de tríceps con mancuerna',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'Mancuernas',
    loadType: 'external',
    loadRatio: 0.04,
    difficulty: 'foundation',
    cues: ['Brazo paralelo al suelo, fijo', 'Extiende solo el antebrazo', 'Pausa arriba con el tríceps contraído'],
  },
  // ---- Tracción ----
  {
    id: 'gym-pull-up',
    name: 'Dominadas',
    modalities: [GYM, CALIS, MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_pull',
    equipment: 'Barra de dominadas',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Agarre prono algo más ancho que hombros', 'Pecho hacia la barra', 'Bajada completa y controlada'],
  },
  {
    id: 'gym-chin-up',
    name: 'Dominadas supinas (chin-up)',
    modalities: [GYM, CALIS, MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_pull',
    equipment: 'Barra de dominadas',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Agarre supino a la anchura de hombros', 'Codos hacia las costillas', 'Sin balanceo'],
  },
  {
    id: 'gym-one-arm-db-row',
    name: 'Remo a un brazo con mancuerna',
    modalities: [GYM, MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_pull',
    equipment: 'Dumbbells + Bench',
    loadType: 'external',
    loadRatio: 0.14,
    difficulty: 'foundation',
    cues: ['Mano y rodilla apoyadas en el banco', 'Tira con el codo hacia la cadera', 'Espalda plana, sin rotar el torso'],
  },
  {
    id: 'gym-tbar-row-supported',
    name: 'Remo en T con apoyo de pecho',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Máquina o barra',
    loadType: 'external',
    loadRatio: 0.3,
    difficulty: 'build',
    cues: ['Pecho firme contra el apoyo', 'Escápulas juntas al final del tirón', 'Sin impulso lumbar'],
  },
  {
    id: 'gym-wide-grip-pulldown',
    name: 'Jalón al pecho agarre ancho',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Polea',
    loadType: 'external',
    loadRatio: 0.2,
    difficulty: 'build',
    cues: ['Agarre ancho prono', 'Barra a la parte alta del pecho', 'Sin recostarse en exceso'],
  },
  {
    id: 'gym-straight-arm-pulldown',
    name: 'Pullover en polea (brazos rectos)',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Polea',
    loadType: 'external',
    loadRatio: 0.1,
    difficulty: 'foundation',
    cues: ['Brazos casi rectos todo el recorrido', 'Lleva la barra a las caderas con los dorsales', 'Core firme, sin balanceo'],
  },
  {
    id: 'gym-db-pullover',
    name: 'Pullover con mancuerna',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Dumbbells + Bench',
    loadType: 'external',
    loadRatio: 0.12,
    difficulty: 'build',
    cues: ['Una sola mancuerna sujeta con ambas manos', 'Arco amplio por detrás de la cabeza', 'Costillas abajo, core activo'],
  },
  {
    id: 'gym-barbell-curl',
    name: 'Curl de bíceps con barra',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Barbell',
    loadType: 'external',
    loadRatio: 0.12,
    difficulty: 'build',
    cues: ['Codos pegados al torso', 'Sin balanceo de cadera', 'Bajada lenta de 2-3 s'],
  },
  {
    id: 'gym-hammer-curl',
    name: 'Curl martillo',
    modalities: [GYM, MIXED],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Mancuernas',
    loadType: 'external',
    loadRatio: 0.07,
    difficulty: 'foundation',
    cues: ['Agarre neutro (palmas enfrentadas)', 'Codos fijos', 'Controla la bajada'],
  },
  {
    id: 'gym-preacher-curl',
    name: 'Curl en banco Scott',
    modalities: [GYM],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'Barra EZ + Banco Scott',
    loadType: 'external',
    loadRatio: 0.08,
    difficulty: 'foundation',
    cues: ['Axilas bien apoyadas en el banco', 'Extiende casi por completo abajo', 'Sin ayudar con los hombros'],
  },
  // ---- Core (osteoporosis-safe: anti-rotación y anti-extensión, sin flexión cargada) ----
  {
    id: 'gym-pallof-press',
    name: 'Press Pallof en polea',
    modalities: [GYM, MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'core',
    equipment: 'Polea o banda',
    loadType: 'external',
    loadRatio: 0.05,
    difficulty: 'foundation',
    cues: ['Perfil a la polea, pies a la anchura de caderas', 'Extiende los brazos sin dejar que el torso rote', 'Respira sin perder la tensión'],
  },
  {
    id: 'gym-ab-rollout-knees',
    name: 'Rueda abdominal de rodillas',
    modalities: [GYM, MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'core',
    equipment: 'Rueda abdominal o barra con discos',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Pelvis en retroversión ligera antes de rodar', 'Avanza solo hasta donde la lumbar no se arquee', 'Vuelve tirando desde el core'],
  },
];
