import { TrainingModality } from '../../domain/models.js';

export const trxYogaCatalog = [
  // TRX
  {
    id: 'trx-row',
    name: 'TRX Row',
    modalities: [TrainingModality.TRX, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_pull',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Cuerpo rígido', 'Codos hacia atrás', 'Controla ángulo para progresar'],
  },
  {
    id: 'trx-chest-press',
    name: 'TRX Chest Press',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_push',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Core estable', 'Codos 45°', 'Progresión por inclinación'],
  },
  {
    id: 'trx-squat',
    name: 'TRX Squat',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_strength',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Cadera atrás', 'Talones firmes', 'Subida controlada'],
  },
  {
    id: 'trx-lunge',
    name: 'TRX Lunge',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_unilateral',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Paso estable', 'Rodilla alineada', 'Evitar colapso medial'],
  },
  {
    id: 'trx-hamstring-curl',
    name: 'TRX Hamstring Curl',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Cadera alta', 'Curl controlado', 'Sin balanceo'],
  },
  {
    id: 'trx-atomic-pushup',
    name: 'TRX Atomic Push-up',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['mixed'],
    category: 'conditioning',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Core rígido', 'Rodillas al pecho', 'Mantén ritmo técnico'],
  },
  {
    id: 'trx-biceps-curl',
    name: 'TRX Biceps Curl',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance'],
    category: 'upper_pull',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Codos altos y fijos', 'Controla el ángulo', 'Evita extender hombros'],
  },
  {
    id: 'trx-triceps-extension',
    name: 'TRX Triceps Extension',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance'],
    category: 'upper_push',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Cuerpo estable', 'Codos al frente', 'Extensión completa sin colapsar hombros'],
  },
  {
    id: 'trx-y-fly',
    name: 'TRX Y Fly',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'recovery'],
    category: 'upper_pull',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Pulgares arriba', 'Escápulas activas', 'Recorrido corto y muy limpio'],
  },
  {
    id: 'trx-power-pull',
    name: 'TRX Power Pull',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_pull',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    cues: ['Rota desde tórax', 'Controla el retorno', 'Hombro estable'],
  },
  {
    id: 'trx-plank-saw',
    name: 'TRX Plank Saw',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'core',
    equipment: 'TRX',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Antebrazos firmes', 'Mueve desde hombros', 'Lumbar neutra todo el tiempo'],
  },
  {
    id: 'trx-chest-fly',
    name: 'TRX Chest Fly',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_push',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Brazos semi flexionados', 'Abre con control', 'Mantén hombros centrados'],
    progressions: ['Mayor inclinación', 'Pausa abierta 2s', 'Tempo lento excéntrico'],
    regressions: ['Menor inclinación', 'Rango parcial', 'Chest press en lugar de fly'],
    contraindications: ['Dolor anterior de hombro', 'Inestabilidad glenohumeral'],
  },
  {
    id: 'trx-reverse-fly',
    name: 'TRX Reverse Fly',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'recovery'],
    category: 'upper_pull',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Pulgares arriba', 'Abre desde espalda alta', 'Evita encoger hombros'],
    progressions: ['Mayor inclinación', 'Pausa final', 'Versión un brazo asistida'],
    regressions: ['Menor inclinación', 'Recorrido corto', 'Y fly más fácil'],
    contraindications: ['Dolor cervical al compensar', 'Dolor agudo de hombro'],
  },
  {
    id: 'trx-fallout',
    name: 'TRX Fallout',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'core',
    equipment: 'TRX',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Costillas abajo', 'Brazos avanzan sin colapsar lumbar', 'Aprieta glúteos'],
    progressions: ['Más recorrido', 'Pausa extendida', 'Base más estrecha'],
    regressions: ['Rango corto', 'Apoyo de rodillas', 'Plank saw'],
    contraindications: ['Dolor lumbar en extensión', 'Diástasis no controlada'],
  },
  {
    id: 'trx-rollout',
    name: 'TRX Rollout',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'core',
    equipment: 'TRX',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Línea corporal larga', 'No dejes caer la pelvis', 'Recupera desde abdomen'],
    progressions: ['Mayor inclinación', 'Tempo 3-1-1', 'Bloques más largos'],
    regressions: ['Fallout corto', 'Base más abierta', 'Menor ángulo'],
    contraindications: ['Lumbalgia reactiva', 'Dolor de hombro por flexión final'],
  },
  {
    id: 'trx-single-leg-squat',
    name: 'TRX Single-Leg Squat',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_unilateral',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Asiste solo lo necesario', 'Cadera baja en línea', 'Rodilla estable'],
    progressions: ['Menor asistencia de brazos', 'Más profundidad', 'Pausa abajo'],
    regressions: ['Toque de punta trasera', 'Rango parcial', 'TRX split squat'],
    contraindications: ['Dolor de rodilla no tolerado', 'Pérdida marcada de equilibrio'],
  },
  {
    id: 'trx-hip-press',
    name: 'TRX Hip Press',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance'],
    category: 'posterior_chain',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Eleva cadera antes de flexionar', 'Talones activos', 'No pierdas la pelvis neutra'],
    progressions: ['Versión unilateral', 'Pausa en extensión', 'Tempo lento'],
    regressions: ['Hip lift isométrico', 'Menor recorrido', 'Hamstring curl bilateral'],
    contraindications: ['Calambres femorales repetidos', 'Dolor lumbar al elevar pelvis'],
  },
  {
    id: 'trx-side-plank',
    name: 'TRX Side Plank',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'recovery'],
    category: 'core',
    equipment: 'TRX',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Cuerpo alineado', 'Cadera alta', 'Respira sin perder tensión lateral'],
    progressions: ['Pierna superior elevada', 'Bloques más largos', 'Versión con reach-through'],
    regressions: ['Side plank en suelo', 'Rodilla inferior apoyada', 'TRX con menor ángulo'],
    contraindications: ['Dolor de hombro lateral', 'Inestabilidad lumbo-pélvica aguda'],
  },
  {
    id: 'trx-pike',
    name: 'TRX Pike',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['mixed', 'resistance'],
    category: 'core',
    equipment: 'TRX',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Eleva caderas desde abdomen', 'Piernas firmes', 'No cierres hombros'],
    progressions: ['Mayor altura de cadera', 'Pike con pausa', 'Pike to press'],
    regressions: ['Rodillas flexionadas', 'TRX knee tuck', 'Plank saw'],
    contraindications: ['Dolor lumbar en flexión', 'Dolor de hombro en carga'],
  },
  {
    id: 'trx-sprinter-start',
    name: 'TRX Sprinter Start',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['mixed'],
    category: 'conditioning',
    equipment: 'TRX',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Inclínate como bloque', 'Impulso potente', 'Cadencia rápida sin perder postura'],
    progressions: ['Bloques más largos', 'Mayor inclinación', 'Series densas'],
    regressions: ['Marcha inclinada', 'Cadencia moderada', 'Menor ángulo'],
    contraindications: ['Aquilodinia reactiva', 'Dolor patelofemoral con impacto'],
  },
  {
    id: 'trx-t-fly',
    name: 'TRX T Fly',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'recovery'],
    category: 'upper_pull',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Abre en línea de hombros', 'Pecho alto', 'Recorrido limpio y corto'],
    progressions: ['Mayor inclinación', 'Pausa final', 'Combinación Y-T fly'],
    regressions: ['Menor inclinación', 'Rango corto', 'Reverse fly básico'],
    contraindications: ['Irritación del manguito rotador', 'Dolor cervical si eleva hombros'],
  },
  {
    id: 'trx-single-arm-row',
    name: 'TRX Single-Arm Row',
    modalities: [TrainingModality.TRX, TrainingModality.MIXED],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_pull',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'trx single arm row proper form tutorial',
    cues: ['Hombros cuadrados al inicio', 'Tira el codo hacia costillas', 'Resiste la rotación del tronco'],
    progressions: ['Mayor inclinación', 'Pausa final 2s', 'Tempo lento excéntrico'],
    regressions: ['Asistencia con brazo libre', 'Menor inclinación', 'TRX row bilateral'],
    contraindications: ['Dolor anterior de hombro', 'Inestabilidad del tronco sin control'],
  },
  {
    id: 'trx-high-row',
    name: 'TRX High Row',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'recovery'],
    category: 'upper_pull',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'trx high row proper form rear delts',
    cues: ['Codos altos pero sin dolor', 'Escápulas activas', 'Recorrido limpio y controlado'],
    progressions: ['Mayor inclinación', 'Pausa atrás', 'Alternar con reverse fly'],
    regressions: ['Menor inclinación', 'Rango parcial', 'TRX row básico'],
    contraindications: ['Pinzamiento subacromial', 'Dolor cervical al encoger hombros'],
  },
  {
    id: 'trx-knee-tuck',
    name: 'TRX Knee Tuck',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'core',
    equipment: 'TRX',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'trx knee tuck proper form tutorial',
    cues: ['Empuja el suelo', 'Rodillas viajan bajo cadera', 'Evita hundir la lumbar'],
    progressions: ['Mayor tiempo', 'Pausa con rodillas al pecho', 'Alternar con pike'],
    regressions: ['Bloques cortos', 'Rodillas menos profundas', 'Plank saw'],
    contraindications: ['Dolor lumbar al flexionar', 'Dolor de hombro en apoyo prolongado'],
  },
  {
    id: 'trx-bulgarian-split-squat',
    name: 'TRX Bulgarian Split Squat',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_unilateral',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'trx bulgarian split squat proper form',
    cues: ['Pie delantero bien anclado', 'Torso levemente inclinado', 'Baja recto sin colapsar rodilla'],
    progressions: ['Más profundidad', 'Menor ayuda de brazos', 'Pausa abajo'],
    regressions: ['TRX split squat simple', 'Rango parcial', 'Apoyo extra con manos'],
    contraindications: ['Dolor patelofemoral marcado', 'Pérdida de equilibrio importante'],
  },
  {
    id: 'trx-curtsy-lunge',
    name: 'TRX Curtsy Lunge',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_unilateral',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'trx curtsy lunge proper form glute',
    cues: ['Cruza la pierna sin girar pelvis', 'Peso firme en pierna de apoyo', 'Sube empujando el suelo'],
    progressions: ['Más rango', 'Menor asistencia', 'Pausa final'],
    regressions: ['Paso más corto', 'Rango parcial', 'TRX reverse lunge'],
    contraindications: ['Dolor medial de rodilla', 'Inestabilidad de cadera'],
  },
  {
    id: 'trx-assisted-pistol-squat',
    name: 'TRX Assisted Pistol Squat',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'lower_body_unilateral',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'trx assisted pistol squat proper form',
    cues: ['Usa las correas solo como asistencia', 'Talón de apoyo pesado', 'Rodilla sigue línea del pie'],
    progressions: ['Menor asistencia', 'Caja más baja', 'Pausa abajo'],
    regressions: ['Box squat unilateral', 'Rango parcial', 'TRX single-leg squat'],
    contraindications: ['Dolor de rodilla en flexión profunda', 'Movilidad de tobillo insuficiente sin control'],
  },
  {
    id: 'trx-glute-bridge',
    name: 'TRX Glute Bridge',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'recovery'],
    category: 'posterior_chain',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'trx glute bridge proper form',
    cues: ['Eleva pelvis en bloque', 'Costillas contenidas', 'Empuja talones hacia correas'],
    progressions: ['Pausa arriba 3s', 'Mayor tiempo', 'Marcha alterna'],
    regressions: ['Puente en suelo', 'Rango corto', 'Apoyo de pies más alto'],
    contraindications: ['Calambre femoral inmediato', 'Dolor lumbar al extender'],
  },
  {
    id: 'trx-hamstring-runner',
    name: 'TRX Hamstring Runner',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'posterior_chain',
    equipment: 'TRX',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'trx hamstring runner proper form',
    cues: ['Cadera alta constante', 'Alterna talones sin perder pelvis', 'Ritmo rápido solo si controlas'],
    progressions: ['Mayor tiempo', 'Cadencia más alta', 'Pausa isométrica cada cambio'],
    regressions: ['TRX hamstring curl', 'Menor tiempo', 'Alternancia lenta'],
    contraindications: ['Aquilodinia reactiva', 'Calambres isquiotibiales repetidos'],
  },
  {
    id: 'trx-hip-hinge',
    name: 'TRX Hip Hinge',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'recovery'],
    category: 'posterior_chain',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'trx hip hinge proper form tutorial',
    cues: ['Bisagra desde cadera', 'Espalda larga', 'Siente carga en isquios y glúteos'],
    progressions: ['Más recorrido', 'Tempo 3-1-1', 'Versión unilateral asistida'],
    regressions: ['Rango corto', 'Mayor apoyo en correas', 'Puente de cadera'],
    contraindications: ['Dolor lumbar al perder neutro', 'Mareo al inclinarse'],
  },
  {
    id: 'trx-oblique-crunch',
    name: 'TRX Oblique Crunch',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'core',
    equipment: 'TRX',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'trx oblique crunch proper form',
    cues: ['Lleva rodilla hacia codo opuesto', 'Hombros empujan el suelo', 'Rotación controlada'],
    progressions: ['Mayor tiempo', 'Pausa en cruce', 'Alternancia más densa'],
    regressions: ['TRX knee tuck', 'Rango corto', 'Bloques cortos'],
    contraindications: ['Dolor lumbar con rotación', 'Dolor de hombro en carga'],
  },
  {
    id: 'trx-crossover-row',
    name: 'TRX Crossover Row',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'mixed'],
    category: 'upper_pull',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'trx crossover row proper form',
    cues: ['Cruza la mano sin perder hombro centrado', 'Gira desde dorsal alto', 'Controla la vuelta'],
    progressions: ['Mayor inclinación', 'Pausa final', 'Alternancia continua'],
    regressions: ['TRX power pull', 'Rango parcial', 'TRX row unilateral asistido'],
    contraindications: ['Inestabilidad glenohumeral', 'Dolor posterior de hombro'],
  },
  {
    id: 'trx-face-pull',
    name: 'TRX Face Pull',
    modalities: [TrainingModality.TRX],
    sessionTypes: ['resistance', 'recovery'],
    category: 'upper_pull',
    equipment: 'TRX',
    loadType: 'bodyweight',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'trx face pull proper form tutorial',
    cues: ['Tira hacia frente de la cara', 'Codos altos sin dolor', 'Rota ligeramente al final'],
    progressions: ['Mayor inclinación', 'Pausa final', 'Tempo más lento'],
    regressions: ['Menor inclinación', 'Rango corto', 'TRX high row'],
    contraindications: ['Dolor agudo del manguito rotador', 'Cervicalgia por compensación'],
  },

  // Yoga
  {
    id: 'yoga-sun-salutation',
    name: 'Sun Salutation Flow',
    modalities: [TrainingModality.YOGA, TrainingModality.MIXED],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Respira por nariz', 'Sin dolor en rangos', 'Transiciones fluidas'],
  },
  {
    id: 'yoga-warrior-sequence',
    name: 'Warrior I/II Sequence',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'mobility_strength',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Cadera estable', 'Rodilla sobre tobillo', 'Control postural'],
  },
  {
    id: 'yoga-chair-pose',
    name: 'Chair Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'lower_body_strength',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Peso en talones', 'Core activo', 'Hombros lejos de orejas'],
  },
  {
    id: 'yoga-tree-pose',
    name: 'Tree Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'neuromotor',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Mirada fija', 'Cadera neutra', 'Respiración lenta'],
  },
  {
    id: 'yoga-child-pose',
    name: 'Child Pose',
    modalities: [TrainingModality.YOGA, TrainingModality.PILATES],
    sessionTypes: ['recovery', 'mindbody'],
    category: 'recovery',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Relajar hombros', 'Respira profundo', 'Sin dolor lumbar'],
  },
  {
    id: 'yoga-cat-cow',
    name: 'Cat-Cow',
    modalities: [TrainingModality.YOGA, TrainingModality.PILATES, TrainingModality.HOME],
    sessionTypes: ['recovery', 'mindbody'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Movimiento vertebral suave', 'Coordina respiración', 'Ritmo continuo'],
  },
  {
    id: 'yoga-downward-dog',
    name: 'Downward Dog',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Empuja el suelo', 'Alarga columna', 'Talones bajan según tolerancia'],
  },
  {
    id: 'yoga-cobra-pose',
    name: 'Cobra Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Extiende sin comprimir lumbar', 'Hombros atrás', 'Activa glúteos suave'],
  },
  {
    id: 'yoga-bridge-pose',
    name: 'Bridge Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Empuje desde talones', 'Rodillas paralelas', 'Eleva esternón sin dolor cervical'],
  },
  {
    id: 'yoga-boat-pose',
    name: 'Boat Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Pecho abierto', 'Lumbar larga', 'Respira sin colapsar abdomen'],
  },
  {
    id: 'yoga-pigeon-stretch',
    name: 'Pigeon Stretch',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['recovery', 'mindbody'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Caderas niveladas', 'Sin dolor anterior de rodilla', 'Respira y suelta tensión'],
  },
  {
    id: 'yoga-half-moon',
    name: 'Half Moon Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'neuromotor',
    equipment: 'Mat o bloque',
    loadType: 'time',
    loadRatio: 0,
    cues: ['Apoyo firme', 'Cadera abre sin perder eje', 'Mirada estable'],
  },
  {
    id: 'yoga-triangle-pose',
    name: 'Triangle Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'mobility_strength',
    equipment: 'Mat o bloque',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Extiende ambos costados', 'Piernas activas', 'Pecho rota sin colapsar lumbar'],
    progressions: ['Sin bloque', 'Mayor tiempo por lado', 'Transición dinámica desde guerrero'],
    regressions: ['Mano más alta', 'Menor apertura de cadera', 'Bloque elevado'],
    contraindications: ['Mareo ortostático', 'Dolor sacroilíaco al rotar'],
  },
  {
    id: 'yoga-extended-side-angle',
    name: 'Extended Side Angle',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'mobility_strength',
    equipment: 'Mat o bloque',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Pierna delantera fuerte', 'Lado largo activo', 'Hombro lejos de oreja'],
    progressions: ['Brazo superior junto a oreja', 'Sin apoyo de mano', 'Entrada desde flow'],
    regressions: ['Antebrazo en muslo', 'Bloque alto', 'Menor profundidad'],
    contraindications: ['Dolor de rodilla delantera', 'Inestabilidad lumbar lateral'],
  },
  {
    id: 'yoga-low-lunge-twist',
    name: 'Low Lunge Twist',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Cadera cuadrada', 'Rota desde dorsal', 'Respira antes de profundizar'],
    progressions: ['Rodilla trasera elevada', 'Más tiempo por lado', 'Brazo en línea completa'],
    regressions: ['Mano apoyada en bloque', 'Rotación parcial', 'Rodilla trasera acolchada'],
    contraindications: ['Dolor anterior de cadera', 'Dolor lumbar con torsión'],
  },
  {
    id: 'yoga-locust-pose',
    name: 'Locust Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Alarga piernas hacia atrás', 'Eleva pecho sin comprimir cuello', 'Glúteos activos con control'],
    progressions: ['Brazos extendidos al frente', 'Bloques más largos', 'Pulsos cortos'],
    regressions: ['Solo pecho o solo piernas', 'Manos al lado del cuerpo', 'Menor altura'],
    contraindications: ['Dolor lumbar reactivo', 'Embarazo avanzado en prono'],
  },
  {
    id: 'yoga-camel-pose',
    name: 'Camel Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Extiende cadera antes de arquear', 'Esternón sube', 'Cuello neutral si es necesario'],
    progressions: ['Manos a talones', 'Pausa más larga', 'Entrada y salida controlada'],
    regressions: ['Manos en sacro', 'Dedos de pies flexionados', 'Rango menor'],
    contraindications: ['Mareo', 'Dolor lumbar con extensión', 'Cervicalgia reactiva'],
  },
  {
    id: 'yoga-garland-pose',
    name: 'Garland Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat o bloque',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Talones lo más pesados posible', 'Pecho abierto', 'Empuja rodillas suavemente'],
    progressions: ['Sin soporte bajo talones', 'Mayor tiempo', 'Transición a cossack'],
    regressions: ['Bloque bajo glúteos', 'Talones elevados', 'Rango parcial'],
    contraindications: ['Dolor agudo de rodilla', 'Limitación severa de tobillo'],
  },
  {
    id: 'yoga-dancer-pose',
    name: 'Dancer Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'neuromotor',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Punto fijo visual', 'Empuja pie atrás y arriba', 'Torso crece antes de inclinarse'],
    progressions: ['Mayor inclinación', 'Agarre más interno', 'Bloques más largos'],
    regressions: ['Tocar pared con mano libre', 'Menor altura de pierna', 'Quad stretch de pie'],
    contraindications: ['Pérdida de equilibrio marcada', 'Dolor lumbar al extender'],
  },
  {
    id: 'yoga-revolved-chair',
    name: 'Revolved Chair',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'mobility_strength',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    cues: ['Rodillas parejas', 'Rota desde dorsal', 'Mantén pelvis estable'],
    progressions: ['Plegaria profunda', 'Más tiempo', 'Entrada desde flow'],
    regressions: ['Chair pose sin torsión', 'Rotación parcial', 'Codo fuera de rodilla solo suave'],
    contraindications: ['Dolor lumbar con torsión', 'Síntomas de rodilla en flexión profunda'],
  },
  {
    id: 'yoga-plank-pose',
    name: 'Plank Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'resistance'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Empuja el suelo', 'Costillas abajo', 'Talones activos hacia atrás'],
    progressions: ['Bloques más largos', 'Shoulder tap controlado', 'Plank to chaturanga'],
    regressions: ['Rodillas apoyadas', 'Apoyo elevado', 'Bloques cortos'],
    contraindications: ['Dolor de muñeca', 'Dolor lumbar al perder control'],
  },
  {
    id: 'yoga-seated-forward-fold',
    name: 'Seated Forward Fold',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['recovery', 'mindbody'],
    category: 'mobility',
    equipment: 'Mat o correa',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Bisagra desde cadera', 'Columna larga', 'No tires de la cabeza'],
    progressions: ['Más tiempo', 'Correa más corta', 'Flexión activa de tobillo'],
    regressions: ['Rodillas flexionadas', 'Sentarse sobre bloque', 'Rango menor'],
    contraindications: ['Dolor neural posterior', 'Irritación lumbar con flexión'],
  },
  {
    id: 'yoga-happy-baby',
    name: 'Happy Baby Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['recovery', 'mindbody'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    cues: ['Sacro pesado', 'Rodillas descienden suave', 'Respira al soltar aductores'],
    progressions: ['Mayor tiempo', 'Balanceo suave lateral', 'Extensión parcial de una pierna'],
    regressions: ['Agarra detrás de muslos', 'Una pierna por vez', 'Rango cómodo'],
    contraindications: ['Dolor agudo de cadera', 'Compresión lumbar si se despega sacro'],
  },
  {
    id: 'yoga-eagle-pose',
    name: 'Eagle Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'neuromotor',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    cues: ['Siéntate sobre la pierna de apoyo', 'Codos altos', 'Respira manteniendo equilibrio'],
    progressions: ['Enlace completo de pie', 'Más tiempo', 'Entrada desde chair pose'],
    regressions: ['Punta del pie libre al suelo', 'Cruce parcial de brazos', 'Apoyo en pared'],
    contraindications: ['Inestabilidad de tobillo marcada', 'Dolor de rodilla al cruzar'],
  },
  {
    id: 'yoga-warrior-iii',
    name: 'Warrior III',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'neuromotor',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'warrior 3 pose proper form yoga',
    cues: ['Cadera de la pierna libre mira al suelo', 'Talón empuja atrás', 'Torso largo y estable'],
    progressions: ['Brazos al frente', 'Más tiempo', 'Entrada desde half moon'],
    regressions: ['Manos en pared', 'Dedos del pie libre rozan el suelo', 'Torso menos inclinado'],
    contraindications: ['Pérdida marcada de equilibrio', 'Dolor lumbar al inclinar'],
  },
  {
    id: 'yoga-revolved-triangle',
    name: 'Revolved Triangle',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'mobility_strength',
    equipment: 'Mat o bloque',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'performance',
    youtubeQuery: 'revolved triangle pose proper form yoga',
    cues: ['Bisagra antes de rotar', 'Cadera posterior avanza', 'Rota desde dorsal y no desde lumbar'],
    progressions: ['Sin bloque', 'Más tiempo', 'Brazo superior vertical estable'],
    regressions: ['Bloque alto', 'Rotación parcial', 'Pyramid pose'],
    contraindications: ['Dolor lumbar con torsión', 'Mareo al inclinarse'],
  },
  {
    id: 'yoga-side-plank-pose',
    name: 'Side Plank Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'resistance'],
    category: 'core',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'side plank pose yoga proper form',
    cues: ['Hombro encima de muñeca', 'Cadera alta', 'Empuja el suelo fuerte'],
    progressions: ['Pierna superior elevada', 'Brazo superior por encima de cabeza', 'Más tiempo'],
    regressions: ['Rodilla inferior apoyada', 'Apoyo en antebrazo', 'Bloques cortos'],
    contraindications: ['Dolor de hombro en carga', 'Dolor lateral lumbar'],
  },
  {
    id: 'yoga-chaturanga-hold',
    name: 'Chaturanga Hold',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'resistance'],
    category: 'upper_push',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'chaturanga hold proper form tutorial',
    cues: ['Codos pegados al torso', 'Hombros no bajan del codo', 'Cuerpo en una línea'],
    progressions: ['Más tiempo', 'Entrada desde plank', 'Tempo excéntrico lento'],
    regressions: ['Rodillas apoyadas', 'Bloques cortos', 'Plank pose'],
    contraindications: ['Dolor anterior de hombro', 'Dolor de muñeca en carga'],
  },
  {
    id: 'yoga-upward-facing-dog',
    name: 'Upward-Facing Dog',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'posterior_chain',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'upward facing dog pose proper form',
    cues: ['Empuja manos y empeines', 'Pecho avanza entre brazos', 'Muslos activos lejos del suelo'],
    progressions: ['Más tiempo', 'Transición fluida con chaturanga', 'Mayor apertura torácica'],
    regressions: ['Cobra pose', 'Menor extensión', 'Apoyo de muslos en suelo'],
    contraindications: ['Dolor lumbar en extensión', 'Síntomas de muñeca'],
  },
  {
    id: 'yoga-lizard-pose',
    name: 'Lizard Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat o bloque',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'lizard pose proper form yoga',
    cues: ['Pie delantero firme', 'Cadera trasera se alarga', 'Respira antes de profundizar'],
    progressions: ['Antebrazos al suelo', 'Rodilla trasera elevada', 'Más tiempo por lado'],
    regressions: ['Manos en bloques', 'Rodilla trasera apoyada', 'Rango cómodo'],
    contraindications: ['Dolor anterior de cadera', 'Molestia medial de rodilla'],
  },
  {
    id: 'yoga-thread-the-needle',
    name: 'Thread the Needle',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'thread the needle pose proper form',
    cues: ['Rota desde dorsal alta', 'Apoya hombro sin colapsar cuello', 'Mantén cadera estable'],
    progressions: ['Brazo libre se extiende', 'Más tiempo', 'Respiración profunda por lado'],
    regressions: ['Rango parcial', 'Almohada bajo hombro', 'Cat-cow previo'],
    contraindications: ['Dolor cervical al apoyar', 'Dolor de hombro en rotación final'],
  },
  {
    id: 'yoga-bound-angle-pose',
    name: 'Bound Angle Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat o bloque',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'bound angle pose proper form yoga',
    cues: ['Columna alta', 'Soles de los pies juntas', 'Rodillas bajan solo hasta donde controles'],
    progressions: ['Más tiempo', 'Inclinar torso con bisagra', 'Bloque menos alto bajo caderas'],
    regressions: ['Sentarse sobre bloque', 'Pies más lejos del pubis', 'Soporte bajo rodillas'],
    contraindications: ['Dolor inguinal agudo', 'Irritación medial de rodilla'],
  },
  {
    id: 'yoga-supine-twist',
    name: 'Supine Twist',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'supine twist yoga proper form',
    cues: ['Hombros pesados', 'Rodillas caen con control', 'Respira sin forzar el rango'],
    progressions: ['Más tiempo', 'Pierna superior extendida', 'Mirada contraria estable'],
    regressions: ['Almohada entre rodillas', 'Rango pequeño', 'Una pierna por vez'],
    contraindications: ['Dolor lumbar con torsión', 'Dolor sacroilíaco agudo'],
  },
  {
    id: 'yoga-standing-forward-fold',
    name: 'Standing Forward Fold',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat o bloque',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'foundation',
    youtubeQuery: 'standing forward fold proper form yoga',
    cues: ['Bisagra desde cadera', 'Peso repartido en ambos pies', 'Cuello relajado'],
    progressions: ['Más tiempo', 'Manos al suelo', 'Piernas más activas'],
    regressions: ['Rodillas flexionadas', 'Manos en bloques', 'Rango parcial'],
    contraindications: ['Mareo ortostático', 'Irritación lumbar en flexión'],
  },
  {
    id: 'yoga-fish-pose',
    name: 'Fish Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody', 'recovery'],
    category: 'mobility',
    equipment: 'Mat o bloque',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'fish pose proper form yoga',
    cues: ['Abre esternón', 'Peso principalmente en codos y antebrazos', 'Cuello largo y cómodo'],
    progressions: ['Piernas extendidas activas', 'Más tiempo', 'Bloque bajo dorsal'],
    regressions: ['Soporte alto bajo espalda', 'Rodillas flexionadas', 'Rango menor'],
    contraindications: ['Cervicalgia reactiva', 'Dolor lumbar en extensión'],
  },
  {
    id: 'yoga-pyramid-pose',
    name: 'Pyramid Pose',
    modalities: [TrainingModality.YOGA],
    sessionTypes: ['mindbody'],
    category: 'mobility_strength',
    equipment: 'Mat o bloque',
    loadType: 'time',
    loadRatio: 0,
    difficulty: 'build',
    youtubeQuery: 'pyramid pose proper form yoga',
    cues: ['Caderas cuadradas', 'Pierna delantera activa', 'Alarga columna antes de bajar'],
    progressions: ['Sin bloques', 'Más tiempo', 'Mayor dorsiflexión del pie delantero'],
    regressions: ['Bloques altos', 'Paso más corto', 'Rodilla delantera suave'],
    contraindications: ['Dolor neural posterior', 'Tensión excesiva de isquios con temblor'],
  },
];
